### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by thumphries** [tmcgilchrist/transformers-either#1]
Feel like adding this to Stackage? Only the package maintainer can do so.

**Comment by thumphries** [comment]
I hate that this is who I've become

**Comment by erikd** [comment]
@thumphries That's actually not correct. My package languauge-javascript is on Stackage and I did not put it there. I did however give someone else my blessing to put it on Stackage.

All that's needed is that @tmcgilchrist also gives his blessing.

**Comment by erikd** [comment]
@thumphries That's actually not correct. My package languauge-javascript is on Stackage and I did not put it there. I did however give someone else my blessing to put it on Stackage.

All that's needed is that @tmcgilchrist also gives his blessing.

**Comment by tmcgilchrist** [comment]
@thumphries feel free to add it and include me as a second contact for stackage.

Don't feel so bad about becoming that person :-)

**Comment by tmcgilchrist** [comment]
This seems to be merged into stackage, closing
