### ISSUE TITLE
bracketEitherT?

### ISSUE THREAD

**Issue by thumphries** [tmcgilchrist/transformers-either#5]
Is there any interest in porting `bracketEitherT'` from `x-either`?

Will happily chuck a PR up if so

Exception and left-safe brackets don't seem to be anywhere on Hackage

**Comment by tmcgilchrist** [comment]
You mean this function 
```haskell
bracketEitherT' :: MonadMask m => EitherT e m a -> (a -> EitherT e m c) -> (a -> EitherT e m b) -> EitherT e m b
...
```

Sure if you'd find it useful. I haven't needed it just yet.

**Comment by thumphries** [comment]
Yeah, would be extremely useful for me. I'll bring what I can across. Think we should just call it `bracketEitherT` since we don't have to worry about source compatibility with `either` anymore

AFAIK there's nothing out there that lets you bracket with EitherT and cleanup on both lefts and exceptions. It comes up as one of the "EitherT is an antipattern" arguments
