### ISSUE TITLE
Need an upload to Hackage

### ISSUE THREAD

**Issue by erikd** [tmcgilchrist/transformers-either#57]
Current dependency bounds include `text (>=1.2 && <1.3)`  and HEAD is `text (>=1.2 && <2.1)` which will suit my purposes.

**Comment by erikd** [comment]
Should also add `ghc-9.6` to the CI build matrix.

PR is https://github.com/tmcgilchrist/transformers-either/pull/58

**Comment by tmcgilchrist** [comment]
Uploaded as 
 * https://hackage.haskell.org/package/transformers-except-0.1.4 and  
 * https://hackage.haskell.org/package/transformers-either-0.1.4
